apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-db
spec:
  serviceName: "clickhouse-service"
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-db
  template:
    metadata:
      labels:
        app: clickhouse-db
    spec:
      containers:
      - name: clickhouse-container
        image: yandex/clickhouse-server:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: clickhouse-db
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
